version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=mbcjavaprojectaws -Dsonar.organization=mbcjavaprojectaws -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3841553c17668569c2f5d3e09bc4eb539f8404fa